language: java

os: linux
jdk: openjdk14
dist: trusty

before_deploy:
  - ./gradlew clean
  - ./gradlew jar -Pgpr.tag=$TRAVIS_TAG
  - ./gradlew publish -Pgpr.user=$GITHUB_USERNAME -Pgpr.key=$GITHUB_TOKEN_EPTCP -Pgpr.tag=$TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_EPTCP
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  name: Easy Packet TCP
  on:
    all_branches: true
    tags: true